"""Add translated_title to summary table

Revision ID: cc999bd9c395
Revises: 80a7b12ab76f
Create Date: 2025-08-22 09:57:17.146666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc999bd9c395"
down_revision: Union[str, Sequence[str], None] = "80a7b12ab76f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "summaries", sa.Column("translated_title", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summaries", "translated_title")
    # ### end Alembic commands ###
